version: '3.8'

services:
  derper:
    build: .
    container_name: derper
    restart: unless-stopped
    ports:
      - "${DERP_HTTP_PORT:-9003}:9003"
      - "${DERP_STUN_PORT:-9004}:9004/udp"
    environment:
      - DERP_HOSTNAME=${DERP_HOSTNAME:-localhost}
      - DERP_HTTP_PORT=${DERP_HTTP_PORT:-9003}
      - DERP_STUN_PORT=${DERP_STUN_PORT:-9004}
      - DERP_VERIFY_CLIENTS=${DERP_VERIFY_CLIENTS:-false}
      - DERP_CERT_MODE=${DERP_CERT_MODE:-manual}
      - DERP_CERT_DIR=${DERP_CERT_DIR:-/var/lib/derper}
      - DERP_LOG_LEVEL=${DERP_LOG_LEVEL:-info}
    volumes:
      - derper_data:/var/lib/derper
      - ./logs:/var/log/derper
    networks:
      - derper_net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9003/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  derper_data:
    driver: local

networks:
  derper_net:
    driver: bridge