name: Build Cross-Platform Binaries

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            name: linux-amd64
          - goos: windows
            goarch: amd64
            name: windows-amd64
            ext: .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Test build
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: 0
      run: |
        echo "Testing build for ${{ matrix.name }}"
        GOBIN=$PWD go install tailscale.com/cmd/derper@v1.82.1
        ls -la derper${{ matrix.ext }}
        echo "✅ Build test passed"